django-event-calendar/event_calendar/event_calendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
]

django-event-calendar/event_calendar/events/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'events'
urlpatterns = [
  path('', views.home, name='home'),
  path('create_event/', views.create_event, name='create_event'),
  path('view_all_events/', views.view_all_events, name='view_all_events'),
  path('edit_event/<int:id>', views.edit_event, name='edit_event'),
  path('delete_event/<int:id>', views.delete_event, name='delete_event'),
  path('view_event/<int:id>', views.view_event, name='view_event')
]

django-event-calendar/event_calendar/events/models.py
from django.db import models
from django.utils import timezone 

class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    starts_at = models.DateTimeField(default=timezone.now)
    ends_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(default=timezone.now)

django-event-calendar/event_calendar/events/forms.py
from django import forms
from .models import *


class EventForm(forms.ModelForm):

  class Meta:
    model = Event
    fields = "__all__"
    widgets = { 
    "starts_at" : forms.DateInput(), 
    "ends_at": forms.DateInput() ,
    'description': forms.Textarea(attrs={'rows': 2})}

django-event-calendar/event_calendar/events/views.py
from django.shortcuts import render, redirect
from .forms import EventForm
from .models import Event

def home(request):
  return render(request, 'pages/home.html')


def create_event(request):
  context = {}
  form = EventForm(request.POST or None, request.FILES or None)

  if form.is_valid():
    form.save()
    return redirect('events:view_all_events')

  context['form'] = form
  return render(request, 'pages/create_event.html', context)



def view_all_events(request):
  context = {
    "events" : Event.objects.all()
  }
  return render(request, 'pages/view_all_events.html', context)


def view_event(request, id):
  context = {
    'event' : Event.objects.get(pk=id)
  }
  return render(request, 'pages/view_event.html', context)


def edit_event(request, id):
  context = {}
  form = EventForm(request.POST or None, request.FILES or None, instance=Event.objects.get(pk=id))

  if form.is_valid():
    form.save()
    return redirect('events:view_all_events')

  context['form'] = form
  return render(request, 'pages/edit_event.html', context)


def delete_event(request, id):
  event = Event.objects.get(pk=id)
  event.delete()
  return redirect('events:view_all_events')

django-event-calendar/event_calendar/events/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}{% endblock %}
  </main>
</body>
</html>

django-event-calendar/event_calendar/events/templates/pages/create_event.html
{% extends 'base.html' %}

{% block content %}
<h1>Creating new</h1>
<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="save" />
</form>


{% endblock %}

django-event-calendar/event_calendar/events/templates/pages/edit_event.html
{% extends 'base.html' %}

{% block content %}
<h1>Editing</h1>
<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="save" />
</form>


{% endblock %}

django-event-calendar/event_calendar/events/templates/pages/home.html
{% extends 'base.html' %}

{% block content %}

<h1>This is Home</h1>
<a href="{ url 'events:create_event' }"

{% endblock %}

django-event-calendar/event_calendar/events/templates/pages/view_all_events.html
{% extends 'base.html' %}
{% block content %}

<ul>
  {% for event in events %}
  <li>{{event.description}}
    <a href="{% url 'events:edit_event' event.id %}">Edit</a>
    <a href="{% url 'events:view_event' event.id %}">View</a>
    <a href="{% url 'events:delete_event' event.id %}">Delete</a>
  </li>
 
  {% endfor %}
</ul>
<a href="{% url 'events:create_event' %}">Create new event</a>
{% endblock %}

django-event-calendar/event_calendar/events/templates/pages/view_event.html
{% extends 'base.html' %}



{% block content %}

<h1>{{event.name}}</h1>
<ul>
  <li>Event Details: {{event.description}}</li>
  <li>Start: {{event.starts_at}}</li>
  <li>Ends: {{event.ends_at}}</li>
  <li>Event created: {{event.created_at}}</li>
</ul>
<a href="{% url 'events:view_all_events' %}" >Go home</a>

<a href="{% url 'events:delete_event' event.id %}">Delete Event</a>

{% endblock %}